export const CvConstants = {
    ERROR_UPLOADING_CV: "Erreur lors du téléchargement du CV",
    ERROR_PDF: "Erreur de PDF",
    FAILED_CANVAS: "Échec du rendu du canevas",
    ERROR_PDF_CV: "Erreur lors de l'analyse du PDF du CV",
    ERROR_LOADING: "Erreur de chargement",
    Ajout_Succes: "CV ajouté avec succès ! 🎉",
    Ajout_Failed: "Une erreur est survenue lors de l'ajout du CV. Veuillez réessayer. ❌",
    Titre_Required: "Le titre du CV est requis",
    Title_Label: "Titre",
    File_Required: "Le fichier est requis",
    selectFileText: "Sélectionnez un fichier ou glissez-déposez ici",
    fileSizeInfo: "PDF, DOC ou DOCX, taille maximale de 10 Mo",
    HEADER_TITLE: "Modifiez votre CV",
    HEADER_SUBTITLE: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent.",
    BREADCRUMB_CVS: "CVs",
    BREADCRUMB_MODIFY: "Modifier un CV",
    BREADCRUMB_ADD: "Ajouter un CV",
    TITLE_PLACEHOLDER: "Modifier le titre de votre CV...",
    ADD_TITLE_PLACEHOLDER: "Ajoutez le titre de votre CV...",
    TITLE_REQUIRED: "Le titre du CV est requis",
    VISIBILITY_LABEL: "Visibilité",
    VISIBILITY_PUBLIC: "Public",
    VISIBILITY_PRIVATE: "Privé",
    UPLOAD_TEXT: "Sélectionnez un fichier ou glissez-déposez ici",
    UPLOAD_HELP: "JPG, PNG ou PDF, taille maximale de 10 Mo",
    SELECT_FILE_BUTTON: "SÉLECTIONNER UN FICHIER",
    BACK_BUTTON: "Annuler",
    SUBMIT_BUTTON: "Soumettre",
    DELETE_SUCCES: "CV supprimé avec succès",
    DELETE_ERROR: "Échec de la suppression du CV",
    WARNING_TEXT: "L'édition est limitée au titre et à la visibilité. Le fichier du CV reste inchangé.",
    CREATION: "Créez le meilleur CV avec nous",
    HIRING: "Recrutez intelligemment, recrutez rapidement",
    HIRING_MESSAGE: "Votre parcours de recrutement commence ici, avec les meilleurs talents.",
    RECRUTER_UPLOAD_CV: "Le CV a été téléchargé avec succès !",
    ERROR_INVALID_PDFURL: "URL de PDF invalide",
    ERROR_INVALID_FORMAT: "Erreur lors de la génération de la miniature du PDF",
    ERROR_FAILED_CANVAS: "Échec de l'obtention du contexte du canevas",
    ERROR_RETRIEVING_CV: "Erreur lors de la récupération des CVs",
    ERROR_RETRIEVING_PDF: "Erreur lors de la récupération du fichier",
    FILE_NOT_FOUND: "Fichier introuvable",
    SHOW_FILE_ERROR: "Erreur dans showFile",
    ERROR_FILE_PATH: "Le chemin du fichier est indéfini",
    ERROR_FILE_HASH: "Le hash du fichier est indéfini",
    ERROR_FILE_UPLOAD: "Échec du téléchargement du fichier",
    ERROR_PDF_TEXT: "Erreur d'extraction de texte depuis le PDF",
    ERROR_INVALID_PDF: "Le fichier fourni n'est pas un PDF valide.",
    ERROR_CANNOT_READ_FILE: "Impossible de lire le fichier.",
    ERROR_TEXT_EXTRACTION: "Erreur d'extraction du texte du PDF.",
    ERROR_PDF_INITIALIZATION: "Impossible d'initialiser le document PDF.",
    ERROR_FILE_READING: "Erreur de lecture du fichier.",
    ERROR_FILE_TYPE: "Type de fichier invalide. Seuls les fichiers PDF, DOC et DOCX sont autorisés.",
    TOASTR_ERROR: "Veuillez téléverser un fichier valide (PDF, DOC ou DOCX).",
    CREATION_MESSAGE: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent",
    SEARCH: "Rechercher",
    SEARCH_PLACEHOLDER: "Ex. DevOps, AWS, PO...",
    MY_CVS: "Mes CVs",
    ALL_CVS: "Tous les CVs",
    ADD_NEW_CV: "Ajouter un CV",
    DELETION_CONFIRMATION: "Êtes-vous sûr de vouloir supprimer votre CV ?",
    ADD_CV_TITLE: "Ajouter un nouveau CV",
    ADD_CV_TEXT: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent.",
    DELETION_TITLE: "Suppression du CV",
    NO_CV: "Aucun CV trouvé. Essayez d'ajouter un nouveau CV ou d'affiner votre recherche.",
    MODIFIER: "Mettre à jour",
    Modify_Succes: "Votre CV a été modifié avec succès ! 🎉",
    Modify_Failed: "Une erreur est survenue lors de la modification du CV. Veuillez réessayer. ❌",
    UPLOAD_STATUSES: {
      NO_FILE_SELECTED: "Aucun fichier sélectionné !",
      FILE_SELECTED: "Fichier sélectionné : ",
      UPLOADING: "Téléchargement en cours...",
      UPLOAD_SUCCESS: "Téléchargement réussi !",
      UPLOAD_FAILED: "Échec du téléchargement."
    },
    LOAD_MORE: "CHARGER PLUS",
    MATTOOL_EDIT: "Modifier",
    MATTOOL_Delete: "Supprimer",
    MATTOOL_Improve: "Améliorer",
    CLOUD_ICON: "",
    BUTTON_EDIT: "",
    BUTTON_DELETE:""
  }
  