export const CvConstants = {
    ERROR_UPLOADING_CV: "Erreur lors du téléchargement du CV",
    ERROR_PDF: "Erreur de PDF",
    FAILED_CANVAS: "Échec du rendu du canevas",
    ERROR_PDF_CV: "Erreur lors de l'analyse du PDF du CV",
    ERROR_LOADING: "Erreur de chargement",
    Ajout_Succes: "CV ajouté avec succès ! 🎉",
    Ajout_Failed: "Une erreur est survenue lors de l'ajout du CV. Veuillez réessayer. ❌",
    Titre_Required: "Le titre du CV est requis",
    Title_Label: "Titre",
    File_Required: "Le fichier est requis",
    selectFileText: "Sélectionnez un fichier ou glissez-déposez ici",
    fileSizeInfo: "PDF, DOC ou DOCX, taille maximale de 10 Mo",
    HEADER_TITLE: "Modifiez votre CV",
    HEADER_SUBTITLE: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent.",
    BREADCRUMB_CVS: "CVs",
    BREADCRUMB_MODIFY: "Modifier un CV",
    BREADCRUMB_ADD: "Ajouter un CV",
    TITLE_PLACEHOLDER: "Modifier le titre de votre CV...",
    ADD_TITLE_PLACEHOLDER: "Ajoutez le titre de votre CV...",
    TITLE_REQUIRED: "Le titre du CV est requis",
    VISIBILITY_LABEL: "Visibilité",
    VISIBILITY_PUBLIC: "Public",
    VISIBILITY_PRIVATE: "Privé",
    UPLOAD_TEXT: "Sélectionnez un fichier ou glissez-déposez ici",
    UPLOAD_HELP: "JPG, PNG ou PDF, taille maximale de 10 Mo",
    SELECT_FILE_BUTTON: "SÉLECTIONNER UN FICHIER",
    BACK_BUTTON: "Annuler",
    SUBMIT_BUTTON: "Soumettre",
    DELETE_SUCCES: "CV supprimé avec succès",
    DELETE_ERROR: "Échec de la suppression du CV",
    WARNING_TEXT: "L'édition est limitée au titre et à la visibilité. Le fichier du CV reste inchangé.",
    CREATION: "Créez le meilleur CV avec nous",
    HIRING: "Recrutez intelligemment, recrutez rapidement",
    HIRING_MESSAGE: "Votre parcours de recrutement commence ici, avec les meilleurs talents.",
    RECRUTER_UPLOAD_CV: "Le CV a été téléchargé avec succès !",
    ERROR_INVALID_PDFURL: "URL de PDF invalide",
    ERROR_INVALID_FORMAT: "Erreur lors de la génération de la miniature du PDF",
    ERROR_FAILED_CANVAS: "Échec de l'obtention du contexte du canevas",
    ERROR_RETRIEVING_CV: "Erreur lors de la récupération des CVs",
    ERROR_RETRIEVING_PDF: "Erreur lors de la récupération du fichier",
    FILE_NOT_FOUND: "Fichier introuvable",
    SHOW_FILE_ERROR: "Erreur dans showFile",
    ERROR_FILE_PATH: "Le chemin du fichier est indéfini",
    ERROR_FILE_HASH: "Le hash du fichier est indéfini",
    ERROR_FILE_UPLOAD: "Échec du téléchargement du fichier",
    ERROR_PDF_TEXT: "Erreur d'extraction de texte depuis le PDF",
    ERROR_INVALID_PDF: "Le fichier fourni n'est pas un PDF valide.",
    ERROR_CANNOT_READ_FILE: "Impossible de lire le fichier.",
    ERROR_TEXT_EXTRACTION: "Erreur d'extraction du texte du PDF.",
    ERROR_PDF_INITIALIZATION: "Impossible d'initialiser le document PDF.",
    ERROR_FILE_READING: "Erreur de lecture du fichier.",
    ERROR_FILE_TYPE: "Type de fichier invalide. Seuls les fichiers PDF, DOC et DOCX sont autorisés.",
    TOASTR_ERROR: "Veuillez téléverser un fichier valide (PDF, DOC ou DOCX).",
    CREATION_MESSAGE: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent",
    SEARCH: "Rechercher",
    SEARCH_PLACEHOLDER: "Ex. DevOps, AWS, PO...",
    MY_CVS: "Mes CVs",
    ALL_CVS: "Tous les CVs",
    ADD_NEW_CV: "Ajouter un CV",
    DELETION_CONFIRMATION: "Êtes-vous sûr de vouloir supprimer votre CV ?",
    ADD_CV_TITLE: "Ajouter un nouveau CV",
    ADD_CV_TEXT: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent.",
    DELETION_TITLE: "Suppression du CV",
    NO_CV: "Aucun CV trouvé. Essayez d'ajouter un nouveau CV ou d'affiner votre recherche.",
    MODIFIER: "Mettre à jour",
    Modify_Succes: "Votre CV a été modifié avec succès ! 🎉",
    Modify_Failed: "Une erreur est survenue lors de la modification du CV. Veuillez réessayer. ❌",
    UPLOAD_STATUSES: {
      NO_FILE_SELECTED: "Aucun fichier sélectionné !",
      FILE_SELECTED: "Fichier sélectionné : ",
      UPLOADING: "Téléchargement en cours...",
      UPLOAD_SUCCESS: "Téléchargement réussi !",
      UPLOAD_FAILED: "Échec du téléchargement."
    },
    LOAD_MORE: "CHARGER PLUS",
    MATTOOL_EDIT: "Modifier",
    MATTOOL_Delete: "Supprimer",
    MATTOOL_Improve: "Améliorer",
    CLOUD_ICON: 'cloud_upload',
    BUTTON_EDIT: "edit",
    BUTTON_DELETE:"delete"
  }
  

export const ChatConstants = {
  APP_NAME: "CVBoost",
  HISTORY_TITLE: "Historique",
  HISTORY_LIMIT: "4/50",
  HISTORY_CLEAR: "Effacer l'historique",
  START_CONVERSATION: "Bonjour utilisateur ! Comment puis-je vous aider aujourd’hui ?",
  THINKING: "Réflexion en cours...",
  ERROR_PROCESSING: "Désolé, une erreur est survenue lors du traitement de votre demande.",
  SELECT_CV_FIRST: "Veuillez d'abord sélectionner un CV.",
  HISTORY_ITEM_1_TITLE: "Créer un formulaire d'accueil",
  HISTORY_ITEM_1_DESC: "Écrire du code (HTML, CSS et JS) pour un simple...",
  HISTORY_ITEM_2_TITLE: "Instructions",
  HISTORY_ITEM_2_DESC: "Comment configurer un réseau Wi-Fi sans fil ?",
  HISTORY_ITEM_3_TITLE: "Carrière",
  HISTORY_ITEM_3_DESC: "Comment organiser efficacement votre journée de travail ?",
  HISTORY_ITEM_4_TITLE: "Carrière",
  HISTORY_ITEM_4_DESC: "Conseils pour améliorer la productivité au travail",
  HISTORY_ITEM_5_TITLE: "Intégration",
  HISTORY_ITEM_5_DESC: "Comment fonctionne l'intelligence artificielle ?",
  CHAT_MESSAGE_1: "Hé ! Écoute",
  CHAT_MESSAGE_2: "J'aime vraiment ton idée, mais je pense qu'on peut faire encore mieux.",
  CHAT_MESSAGE_3: "Je vais partager quelque chose",
  CHAT_MESSAGE_4: "Travaillons ensemble pour créer quelque chose d'encore plus génial.",
  CHAT_MESSAGE_5: "Peux-tu venir chez moi vers 20h ce soir ?",
  CHAT_MESSAGE_6: "J'y serai",
  CHAT_MESSAGE_7: "Génial ! Hâte de collaborer avec toi.",
  CHAT_MESSAGE_8: "Moi aussi ! J’ai quelques idées excitantes à discuter.",
  CHAT_MESSAGE_9: "Parfait ! N'oublie pas d'apporter ton ordinateur portable.",
  CHAT_MESSAGE_10: "Déjà prêt ! J'apporte aussi quelques maquettes de design.",
  CHAT_MESSAGE_11: "C'est exactement ce qu'il nous faut ! Nous pourrons les examiner ensemble.",
  CHAT_MESSAGE_12: "J'ai aussi préparé une présentation sur les nouvelles fonctionnalités.",
  CHAT_MESSAGE_13: "Excellente préparation ! Cela rendra notre réunion très productive.",
  CHAT_MESSAGE_14: "Merci ! Je suis vraiment enthousiaste pour ce projet.",
  CHAT_MESSAGE_15: "Ton enthousiasme est contagieux ! Créons quelque chose d’incroyable.",
  CHAT_MESSAGE_16: "Absolument ! À ce soir !",
  CV_ANALYSIS: "Analyse de CV",
  SKILLS_MATCH: "Correspondance des compétences",
  EXPERIENCE_LEVEL: "Niveau d'expérience",
  EDUCATION_MATCH: "Correspondance des études",
  LANGUAGE_SCORE: "Niveau de langue",
  SKILLS_MATCH_VALUE: "92%",
  EXPERIENCE_LEVEL_VALUE: "85%",
  EDUCATION_MATCH_VALUE: "98%",
  OVERALL_SCORE_VALUE: "88%",
  MESSAGE_PLACEHOLDER: "Tapez un message",
  SEARCH_PLACEHOLDER: "Rechercher",
  USER_NOT_FOUND: "Utilisateur non défini ou ID manquant, annulation de la suppression.",
  Interaction_Missing: "Objet d'interaction manquant, impossible d'effacer l'historique.",
  Title: "Effacer tout l'historique",
  Message: "Êtes-vous sûr de vouloir effacer tout l'historique de discussion ? Cette action est irréversible.",
  CHATS_AVAILAIBILTY: "Aucun chat disponible",
  ICON_DELETE: 'delete',
  ICON_SEARCH:'search',
  ICON_NOTIF:'notifications',
  ICON_HISTORY:'history',
  ICON_FILE:'attach_file',
  ICON_NAVIGATE:'navigate_next',
  ICON_ADD:'add',
  ERROR_DELETING_HISTORY: "Erreur lors de la suppression de l'historique",
  ERROR_DETAILS: "Détails de l'erreur",
  ERROR_REFRESHING_CHAT: "Erreur lors de l'actualisation des données du chat",
}