export const AuthentificationConstant = {
  EMAIL_LABEL: 'Email:',
  EMAIL_REQUIRED_ERROR: 'Email Required.',
  REQUEST_RESET_CODE: 'Request reset code',
  VERIFICATION_CODE_LABEL: 'Verification code:',
  VERIFICATION_CODE_PLACEHOLDER: 'Enter verification code',
  CODE_REQUIRED_ERROR: 'Code is required.',
  NEW_PASSWORD_LABEL: 'New password:',
  NEW_PASSWORD_LENGTH_ERROR: 'Password must be at least 8 characters long.',
  SUBMIT_NEW_PASSWORD: 'Submit new password',
  ERROR_SIGN_IN:'An error occurred during sign-in',
  REGISTER_DETAILS_SENTSE:'Register with your personal details to use all of site features',
  PERSONAL_DETAILS_SENTSE:'Enter your personal details to use all of site features',
  WELCOME_BACK:"Welcome Back!",
  HELLO_FRIEND:'Hello, Friend!',
  REGISTRATIONSENTSE:"or use your email for registeration",
  CREATEACCOUNT:"Create Account",
  PASSWORD:"Password",
  PASSWORD_HINT:"Must be at least 8 characters long",
  FORGOT_PASSWORD:"→ Forget Your Password? ←",
  LogIn:"LogIn",
  SIGNIN: 'Sign In',
  SIGNUP: 'Sign Up',
  HINT_EMAIL:'Errors appear instantly!',
  TITLE: 'Get Started With Your Account',
  PASSWORD_LABEL: 'Password:',
  PASSWORD_LENGTH_ERROR: 'Password must be at least 6 characters',
  FORGET_PASSWORD_TEXT: 'Forget password?',
  RESET_LINK: 'Reset',
  NO_ACCOUNT_TEXT: "Don't have an account?",
  EMAIL_INVALID_ERROR: 'Email format is invalid',
  CONFIRM_PASSWORD: 'Confirm Password:',
  PASSWORD_MUST_MATCH: 'Passwords must match',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
  SIGN_UP_SUCCESS: 'A confirmation email has been sent to your email address.',
  USER_ALREADY_EXISTS: 'The user already exists.',
  UNKNOWN_ERROR: 'An unknown error occurred.',
  RECAPTCHA_NOT_VERIFIED: 'Verify recaptcha.',
  RECAPTCHA_ERROR:'Captcha key not found in configuration.',
  LOGIN_SUCCESS: 'Login successful.',
  INVALID_CREDENTIALS: 'Invalid credentials.',
  USER_NOT_FOUND: 'User does not exist.',
  SERVER_UNREACHABLE: 'Cannot reach the server.',
  ERROR_TITLE: 'Error',
  INVALID_FORM: 'Please fill out all form fields correctly.',
  INVALID_FORM_TITLE: 'Invalid Form',
  USER_SIGNED_UP_SUCCESS: 'User signed up successfully',
  USER_CREATION_FAILED:
    "Échec de la création de l'utilisateur, aucun ID valide retourné.",
  VERIFICATION_CODE_SENT: 'A verification code has been sent to your email.',
  VERIFICATION_CODE_FAILED: 'Failed to send the verification code.',
  PASSWORD_RESET_SUCCESS:
    'Password reset successful. You can now sign in with your new password.',
  PASSWORD_RESET_SUCCESSFUL: 'Password reset successful.',
  PASSWORD_REST_FAILED: 'Error in password reset.',
  USER_NOT_FOUND_ID:
    "Aucun ID valide n'a été retourné pour l'utilisateur créé.",
  SENT_VERIFICATION_CODE: 'Verification code sent.',
  CURRENT_USER_LOCAL_STORAGE: 'currentUser',
  USER_NAME:'Username',
  USER_NAME_REQUIRED:'username is required',
  PASSWORD_REQUIRED: ' Password is required',
  USER_MIN_LENGTH:'username must be at least 3 characters ',
  ERROR_SIGN_UP:'',
  ERROR_INVALID_COGNITO_RESPONSE: 'Invalid Cognito user response during signup.',
  ERROR_RECAPTCHA : 'Captcha key not found in configuration.',
};
