export const AuthentificationConstant = {
  EMAIL_LABEL: 'Email',
  EMAIL_REQUIRED_ERROR: 'Email obligatoire.',
  REQUEST_RESET_CODE: 'Request reset code',
  VERIFICATION_CODE_LABEL: 'Verification code:',
  VERIFICATION_CODE_PLACEHOLDER: 'Entrer la verification du code',
  CODE_REQUIRED_ERROR: 'Code obligatoire',
  NEW_PASSWORD_LABEL: 'Nouveau mot de passe', 
  NEW_PASSWORD_LENGTH_ERROR: 'Mot de passe doit contenir 6 caractére au minimum',
  SUBMIT_NEW_PASSWORD: 'Entrer nouveau mot de passe',
  ERROR_SIGN_IN:'An error occurred during sign-in',
  REGISTER_DETAILS_SENTSE:'Inscrivez-vous avec vos informations personnelles pour profiter de toutes les fonctionnalités du site',
  PERSONAL_DETAILS_SENTSE:'Saisissez vos informations personnelles pour accéder à toutes les fonctionnalités du site',
  WELCOME_BACK:"Bon retour !",
  HELLO_FRIEND:'Bonjour !',
  REGISTRATIONSENTSE:"or use your email for registeration",
  CREATEACCOUNT:"Create Account",
  PASSWORD:"Mot de passe",
  PASSWORD_HINT:"Mot de passe doit contenir 6 caractére au minimum",
  FORGOT_PASSWORD:"→ Mot de passe oublié ? ←",
  LogIn:"Connexion",
  SIGNIN: 'Connexion',
  SIGNUP: 'Inscription',
  HINT_EMAIL:'Errors appear instantly!',
  TITLE: 'Get Started With Your Account',
  PASSWORD_LABEL: 'Mot de passe',
  PASSWORD_LENGTH_ERROR: 'Mot de passe doit contenir 6 caractére au minimum',
  FORGET_PASSWORD_TEXT: 'Mot de passe oublié ?',
  RESET_LINK: 'Réinitialiser',
  NO_ACCOUNT_TEXT: "Vous n'avez pas de compte ?",
  EMAIL_INVALID_ERROR: 'Le format de l"email est invalide',
  CONFIRM_PASSWORD: 'Confirmez le mot de passe :',
  PASSWORD_MUST_MATCH: 'Les mots de passe doivent correspondre',
  ALREADY_HAVE_AN_ACCOUNT: 'Vous avez déjà un compte ?',
  SIGN_UP_SUCCESS: 'Un email de confirmation a été envoyé à votre adresse.',
  USER_ALREADY_EXISTS: 'L"utilisateur existe déjà.',
  UNKNOWN_ERROR: 'Une erreur inconnue est survenue.',
  LOGIN_SUCCESS: 'Connexion réussie.',
  INVALID_CREDENTIALS: 'Identifiants invalides.',
  USER_NOT_FOUND: 'L"utilisateur n"existe pas.',
  SERVER_UNREACHABLE: 'Impossible de contacter le serveur',
  ERROR_TITLE: 'Erreur',
  INVALID_FORM: 'Veuillez remplir correctement tous les champs du formulaire.',
  INVALID_FORM_TITLE: 'Formulaire invalide',
  USER_SIGNED_UP_SUCCESS: 'Inscription réussie',
  USER_CREATION_FAILED:"Échec de la création de l'utilisateur, aucun ID valide retourné.",
  VERIFICATION_CODE_SENT: 'Un code de vérification a été envoyé à votre adresse e-mail.',
  VERIFICATION_CODE_FAILED: 'Échec de l’envoi du code de vérification.',
  PASSWORD_RESET_SUCCESS: 'Réinitialisation du mot de passe réussie. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
  PASSWORD_RESET_SUCCESSFUL: 'Réinitialisation du mot de passe réussie.',
  PASSWORD_REST_FAILED: 'Erreur lors de la réinitialisation du mot de passe.',
  USER_NOT_FOUND_ID:"Aucun ID valide n'a été retourné pour l'utilisateur créé.",
  SENT_VERIFICATION_CODE: 'Code de vérification envoyé.',
  CURRENT_USER_LOCAL_STORAGE: 'currentUser',
  USER_NAME:'Nom d’utilisateur',
  USER_NAME_REQUIRED:'Le nom d’utilisateur est requis',
  PASSWORD_REQUIRED: ' Le mot de passe est requis',
  USER_MIN_LENGTH:'Le nom d’utilisateur doit contenir au moins 3 caractères ',
  ERROR_SIGN_UP: "",
  SIGNUP_ERROR: "Erreur d'inscription",
  SIGNUP_SUCCESSFUL: "Inscription réussie",
  SIGNIN_BUTTON: "Se connecter",
  SIGNUP_BUTTON: "S'inscrire",
  EMAIL_PLACEHOLDER: "email@exemple.com",
  PASSWORD_PLACEHOLDER: "Mot de passe",
  ROLE_LABEL: 'Sélectionnez votre rôle',
ROLE_REQUIRED: 'Le rôle est requis',
 
};
