export const NavbarConstants = {
  OUR_OFFERS: 'Nos Offres',
  JOB_OFFERS: "Offres d'emploi",
  CV: 'Mes CVs',
  FOR_RECRUITERS: 'CVs',
  ABOUT: 'Contactez-Nous',
  HOME: 'Accueil',
 // Profile Menu
 PROFILE_MENU: {
  HEADER: 'Mon Profile',
  SECURITY: 'Securité',
  LOGOUT: 'Déconnexion',
},
 // Icons
 ICONS: {
  REORDER: 'reorder',
  PROFILE: 'person_outline',
  WORK: 'work',
  HOME: 'home',
  BUSINESS_CENTER: 'business_center',
  PEOPLE: 'people',
  DESCRIPTION: 'description',
  CONTACT_SUPPORT: 'contact_support',
  PERSON_OUTLINE: 'person_outline',
  SECURITY: 'security',
  LOGOUT: 'logout',
},
  EMAIL_LABEL: 'Email:',
  NO_ACCESS: 'Could not access properties',
  INVALID_FORMAT: 'Invalid email format',
  INVALID_EMAIL: 'Invalid email address',
  BROWSE_CAREERS: 'Browse Careers',
  I_RECRUIT: 'I Recruit',
  SIGN_IN: 'Sign In',
  CURRENT_USER_LOCAL_STORAGE:'currentUser',
  LOGO_PATH: 'assets/carreerLogo.png',
  USER_AVATAR_PATH: './assets/UserAvatar.png',
};