export const AjoutJobOfferConstants = { 
    TITLE: "Ajouter une nouvelle offre d'emploi",
    TITLE_2: "Mettre à jour une offre d'emploi",
    SMALL_TITLE: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent.",
    ROUTE_OFFRES: "Offres",
    ADD_OFFRES: "Ajouter une offre d'emploi",
    TITLE_LABEL_1: "TITRE",
    TITLE_LABEL_2: "URL",
    RETOUR: "Retour",
    VALIDER: "Soumettre",
    UPDATE_OFFRE: "Modifier une offre d'emploi",
    UPDATE_ERROR_TOAST: "L'offre  ne peut pas être vide, Erreur ❌",
    UPDATE_SUCCESS_TOAST: "L'offre a été changé avec succès, Succès 🎉",
    COMPANY_LABEL: "Entreprise",
    LOCATION_LABEL: "Emplacement",
    TECHNOLOGIES_LABEL: "Technologies",
    SKILLS_LABEL: "Compétences",
    LEVEL_LABEL: "Sélectionner le niveau d'expérience",
    PUBLISHED_DATE_LABEL: "Sélectionner la date de publication",
    EXPIRATION_DATE_LABEL: "Sélectionner la date d'expiration",
    VISIBILITY_LABEL: "Visibilité",
    PUBLIC_LABEL: "Public",
    PRIVATE_LABEL: "Privé",
    ADVANCED_DETAILS: "Détails avancés",
    OFFER_TITLE_PLACEHOLDER: "Ajoutez un titre à votre offre ...",
    OFFER_URL_PLACEHOLDER: "Ajoutez une URL à votre offre ...",
    COMPANY_NAME_PLACEHOLDER: "Entrez le nom de l'entreprise...",
    JOB_LOCATION_PLACEHOLDER: "Entrez le lieu du poste...",
    TECHNOLOGIES_PLACEHOLDER: "Technologies (séparées par des virgules)",
    SKILLS_PLACEHOLDER: "Compétences (séparées par des virgules)",
    EXPERIENCE_LEVEL_LABEL: "Sélectionnez le niveau d'expérience",
    JUNIOR_LEVEL: "Junior",
    SENIOR_LEVEL: "Senior",
    EDIT_OFFER_TITLE_PLACEHOLDER: "Modifier le titre de votre offre ..."
}  