export const JobOfferConstant = {
  ERROR_CANDIDATURE_NOT_LOADED: "La candidature n'a pas pu être chargée",
  ERROR_LOADING_CANDIDATURE: "Erreur lors du chargement de la candidature",
  VERIFICATION_STATUS: "Vérification du statut...",
  ERROR_LOADING_CVS: "Erreur lors du chargement des CVs",
  WARNING_SELECT_CV: "Veuillez sélectionner un CV",
  ERROR_CV_NOT_FOUND: "CV introuvable",
  SUCCESS_CV_UPDATED: "CV mis à jour avec succès",
  SUCCESS_CV_DB_ONLY: "CV mis à jour (base de données seulement)",
  ERROR_UPDATE_FAILED: "Échec de la mise à jour",
  WARNING_NO_IDENTIFIER: "Aucun identifiant fourni",
  CONVERSATION_ALREADY_EXISTS: "Vous avez déjà passé un entretien",
  CONVERSATION_CHECK_ERROR: "Erreur lors de la vérification de la conversation",
  CONVERSATION_CHECK_ERROR_MESSAGE: "Erreur lors de la vérification du statut de l'entretien",
  CURRENT_CV: "CV actuel",
  MODIFY_CV: "Modifier le CV",
  SELECT_NEW_CV: "Sélectionner un nouveau CV",
  CONFIRM_UPDATE: "Confirmer la mise à jour",
  UPDATING: "Mise à jour en cours",
  CANCEL: "Annuler",
  WANT_CHANGE_CV_BEFORE_INTERVIEW: "Modifier le CV avant l'entretien",
  CV_MANAGEMENT_TITLE: "Gestion des CV",
  AVAILABLE_CVS: "CV disponibles",
  CURRENT_LABEL: " CV Actuel",
  EDIT_CV: "Modifier le CV",
  NO_OTHER_CVS: "Aucun autre CV disponible",
  LOADING_CVS: "Chargement des CV...",
  CHANGE_CV: "Changer de CV",
  SUCCESS_DELETING_OFFER: "Offre d'emploi supprimée avec succès",
  FAILED_TO_COPY: " ÉCHEC DE LA COPIE DU LIEN ",
  LINK_COPIED: " Lien copié dans le presse-papiers ",
  UNABLE_COPY_LINK: "Impossible de copier le lien - titre du poste manquant",
  ERROR_MISSING_JOB_TITLE: "Offre d'emploi ou titre manquant",
  EXPERIENCE_LEVEL: " Niveau d'expérience",
  APPLY_MESSAGE: "Saisissez cette opportunité passionnante et faites évoluer votre carrière.",
  PUBLISHED: "Publié",
  UNKNOWN: "Inconnu",
  JOB_INFORMATION: "Informayions sur la poste",
  QUICK_FACTS: "Informations Clés ",
  READY_TO_APPLY: "Prêt(e) à postuler ?",
  ABOUT: "À PROPOS DE",
  BACK_TO_OFFERS: " Retour aux offres ",
  GENERATE_REPORT_SUCCESS: "génerer avec succes",
  LOADING_REPORT: "Chargement du rapport",
  GENERATE_REPORT: "Générer le rapport",
  COPY_LINK: "Copier le lien",
  NO_REPORT_AVAILABLE: "Aucun Rapport",
  EVALUATION_REPORT: "Rapport evaluation",
  VIEW_REPORT: "voir le rapport",
  BUTTON_UPDATE_OFFER: "Mettre à jour l'offre",
  COMPANY_NAME: "Entreprise",
  LOCATION: "Localisation",
  JOB_TECHNOLOGIES: "Technologies",
  OFFER_PUBLISHED: "OFFRE PUBLIÉE :",
  OFFER_EXPIRED: "OFFRE EXPIRÉE LE :",
  LEVEL: "NIVEAU :",
  SKILLS: "Compétences",
  DESCRIPTION: "Description",
  SALARY: "Salaire",
  START_DATE: "Date début",
  DATE: "Date",
  JOB_OFFER_SLOGAN: "Des centaines d'offres d'emploi adaptées à vos compétences vous attendent.",
  OFFER_TITLE: "Offres disponibles",
  BREADCRUMB_OFFER: "Offres",
  BUTTON_ADD_OFFER: "Ajouter offre",
  EDIT_SPAN: "Modifier",
  DELETE_SPAN: "Supprimer",
  DIALOG_TITLE: "Choisir un CV",
  CANCEL_BUTTON: "Annuler",
  SUBMIT_BUTTON: "Soumettre",
  CONF_TITLE: "Confirmation de candidature",
  INTERVIEW_MESSAGE: "Vous aurez un entretien dans les 24 heures.",
  PHONE_INSTR: "Veuillez nous appeler au",
  IDENTIFIER_INSTRUCTION: "Et fournissez l'identifiant :",
  IDENTIFIER_INST: "pour accéder à votre entretien.",
  DO_NOT_LOSE_IDENTIFIER: "Ne le perdez pas pour accéder à l'entretien.",
  POPUP_IDENTIFIER_MESSAGE: "Après la validation de votre candidature, vous recevrez un identifiant dans une nouvelle fenêtre. Veuillez patienter quelques secondes avant de quitter la page pour le récupérer.",
  VALIDATE_BUTTON: "OK",
  HEADER_TITLE: "Bonjour, merci d'avoir postulé pour cet emploi.",
  VISIBILITY: "Filtrer par visibilité :",
  DOWNLOAD_BUTTON: "Télécharger",
    BUTTON_TEXTSMS: 'textsms BUTTON',
  BUTTON_PHONE: 'phone button',
  BUTTON_MIC: 'mic button',

  FAILED_LOAD_JOB_OFFER: "Échec du chargement des détails de l'offre.",
  PHONE_DIAL: "Appel téléphonique",
  CVS_LIST: "Liste des CVS",
  BACK: "Retour",
  LOAD_MORE: "Charger plus",
  CANDIDATES: "Candidats",
  LOADING_CANDIDATES: "Chargement des candidats...",
  NO_CANDIDATES: "Aucun candidat trouvé pour cette offre d'emploi.",
  DOWNLOAD_REPORT: "Télécharger le rapport",
  DOWNLOAD_CV: "Télécharger le CV",
  AUDIO_INTERVIEW: "Entretien audio",
  APPLY_DIALOG_TITLE: "Sélectionner le type d'entretien",
  SELECT_INTERVIEW_TYPE: "Veuillez sélectionner votre type d'entretien préféré :",
  CALL_OPTION: "Entretien téléphonique",
  AUDIO_OPTION: "Entretien audio",
  TEXT_OPTION: "Entretien écrit",
  PROCEED_BUTTON: "Continuer",
  FEATURE_IN_PROGRESS: "Cette fonctionnalité est en cours de développement",
  ALREADY_APPLIED: "Vous avez déjà postulé à cette offre d'emploi.",
  CANDIDATES_LABEL: "Candidats",
  APPLY_LABEL: " Postuler",
  JOB_DESCRIPTION: "Description du poste",
  JOB_SALAIR: "Salaire",
  JOB_DURECONTRAT: "Durée du contrat",
  JOB_DATEDEBIT: "Date de début",
  SHOWSTATIQUE: "Afficher le rapport statique",
  SHOWCV: "Afficher le CV Généré",
  WELCOME_TO_THE_JUNGLE: 'Welcome to the Jungle',
  DROP_ICON: 'more_vert',
  EDIT_ICON: 'edit',
  DELETE_ICON: 'delete',
  CLOSE_ICON: 'close',
  DESC_ICON: 'description',
  ASSIGNMENT_ICON : 'assignment_turned_in',
  CLOUD_ICON: 'cloud_upload',


  CHECK_ICON: 'check_circle',
  PHONE_NUMBER:'+1 775 257 6928',
  VISIBILITY_FILTER: {
    All: "Toutes les offres",
    Public: "Postulé",
    Postuler: "Postuler",
    Private: "Mes offres"
  },

  DELETE_UNAUTHORIZED: "Vous n'êtes pas autorisé à supprimer cette offre d'emploi.",
  UPDATE_UNAUTHORIZED: "Vous n'êtes pas autorisé à modifier cette offre d'emploi."
}